local: &local
  adapter: postgresql
  prepared_statements: false
  encoding: unicode
  username:
  password:
  host: localhost

development:
  primary:
    <<: *local
    database: sample_development
  leader:
    <<: *local
    database: sample_development
    replica: true
